jobs:
  include:
  - language: python
    name: Linux - Python 3.6
    os: linux
    python:
    - '3.6'
    -
  - before_install:
    - choco install python --version 3.6
    - python --version
    - python -m pip install --upgrade pip
    - pip3 install wheel || pip install wheel
    env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    language: shell
    name: Windows - Python 3.6
    os: windows
    after_success:
    - python3 -m pip install twine --user || python -m pip install twine --user


install:
- pip3 install . --use-feature=in-tree-build || pip install . --use-feature=in-tree-build
script:
- python3 setup.py bdist_wheel sdist || python setup.py bdist_wheel sdist
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: __token__
  password:
    secure: Vm/R6xjUlrZgWEnOB0c9EqDwpWgLHwDrlz1SESoD2Jvv3PsEphnIA8X0cJ0nWEMwy/858PTz4Rf5L+62ftwA6mimeWuNMWSf6Tw2DY2CYXj1WSxUKHCS+8dp4GHluYS8kE0zdPvzjMcqQY9gki2gCYR768kQMSnloTVmecBypqpOXdUQqzXgNfIW41vflx4wKYysftsq+OrU3I7iQxAWr+xMxD/RgPOP2stGztepDqryOrPw5aKUp2O/ERWdBseLUKvYpbEqlT2JdbXpkEbkK/QivtpHWC0ME+GObZnrh7rjqJmQnOXO6Bjiqzgordi/SBeLjZaoHrTyz1AsS+W9gTpuju4TNZ+e6Egc7tKwds9LCCVOfdWWYTcuicQbVGQQDTe7poGOmGiDFH2lI/Kv86am46SoJ4mGQBhOB+1XVAPmaiVavnH40gKtFV0ABCHqxrSxeGboCRVwxVo7g7McJpdYdoPrzYMFMY/WaB4YHz8WgvWkX9P8E3GQb7ax7L9iu+ZAwcQnMzUmvr+EtRdy0wrbDJaCQX2HL4egab+KZbtstmJ9V2fYLbzy458Uc2/Xbfm3gZekRggOKTJ7Tm8jGuKz5byZmwpHL5A975q03XXI1htX7mEm4MuNMreHkwDbkFi5cp8m8iHdLoRf+6fvXE58F+uUmTKFPLSsIuIXXRc=
  skip_cleanup: true
  on:
    tags: false
  skip_existing: true
