jobs:
  include:
  - language: python
    name: Linux - Python 3.6
    os: linux
    python:
    - '3.6'
  - before_install:
    - choco install python --version 3.6
    - python --version
    - python3 -m pip3 install --upgrade pip || python -m pip install --upgrade pip
    - pip3 install wheel || pip install wheel
    env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    language: shell
    name: Windows - Python 3.6
    os: windows
    after_success:
    - python3 -m pip install twine --user || python -m pip install twine --user
install:
- pip3 install . || pip install .
script:
- python3 setup.py bdist_wheel sdist || python setup.py bdist_wheel sdist
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: __token__
  password:
    secure: ingQXrd32ic5szk+9WZmhWl5xFJpAfKe1AxV+ZOwYnJ/YYvUioDG+7JAzfbkzwJKDXioeKROb578QYgVXBkfx/qjME4LwKGOJZesZBBxKggUbzWUy38jvxrDixZQqmTL845btzrYkHEuQoKOyLPwkBcstXmcr9BG+LJs1bN4SICmiV1UtQHI+ypBrDp702qvV9y+heMitSUUsL0LsWp07iT0U7CMqZMUb9ZAi+P0kqji5oU4chyj6kIg8nRHyyi1GhdLnUHHo9G/2/rrudqM+oZAroa9yRkY3/O1Tf6RRal4CCU+CDMKpEHgHBECuCYC/cy/vDqfPVG6PAfzU00Oc8fThQpHY5S2vDu/E5MN4KbLdzalGGJ9kWPQIebjdPs7S78e/iIKLuu4CIG07W9GDqqBnL+6jqJqQrAHJ4JQlni5lJenLNM7O2AS54huEtG1DBmCFzTOVh9AVDJCF9i4TuFY1jefvTelAmk/qUuwGGF24Bm4AoMJlytc4TD875WZWzPnCh0DCDm0mhPYcdnkaCo9TQbT+jW80bcwPq/yZzrrAKIWov4z5ZoIDGrvXMNIMuXXqHTKP9f8r0UZl8PUvXl5t+BRIOO66ZboTGd8N2koasuUPXZK6JAyXZthLN5jjAxEEivQK9kfmOVdMfp+hEDdIlxlSHzK1UJlvZkcj90=
  skip_cleanup: true
  on:
    tags: false
  skip_existing: true
